export const KANBAN_REDUCER = "KANBAN_REDUCER";
export const SET_PROJECT_LIST = "SET_PROJECT_LIST";
export const SET_STATUS_LOADING_PROJECT_LIST =
  "SET_STATUS_LOADING_PROJECT_LIST";

export const SET_BOARDDATA = "SET_BOARDDATA";

export const SET_NEW_CATEGORY = "SET_NEW_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";

export const SET_NEW_TASK = "SET_NEW_TASK";
export const DELETE_TASK = "DELETE_TASK";
export const CLOSE_TASK = "CLOSE_TASK";
export const CHANGE_STATUS_TASK = "CHANGE_STATUS_TASK";

export const CHANGE_STATUS_UPLOAD_FILE = "CHANGE_STATUS_UPLOAD_FILE";
export const SET_MEMBERS = "SET_MEMBERS";
